language: node_js
node_js:
  - '6'
  - '8'
  - '10'
before_install:
  - 'npm install -g npm@6'
before_script:
  - sleep 15
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
